name: analysis
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: joeconway <joeconway3@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: any

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
